name: Github Actions

on:
  # schedule:
  #   # Cron schedule expression "minutes hours dayOfThemounth mounth dayOfTheWeek"
  #   # https://crontab.guru/ cool tool
  #   # https://crontab.guru/examples.html examples
  #   # "1 * * * *" ex: will run at minute 1 every hour (* any time)
  #   # "1,2 * * *" minute 1 & 2
  #   # "1-5 * * *" from minute 1 to 5
  #   # "0/15 * * *" from minute 0 and step is 15
  #   - cron: "1 * * * *"
  # push:
  workflow_dispatch: # manually trigger -> can accept inputs
  repository_dispatch: # trigger workflow by post request
    types:
      - blabla # specified in the post request body
  pull_request:
    types:
      - opened
      - reopened
      - assigned
      - closed

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List Files
        run: ls -a

      - name: Simple JavaScript Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Mo'men Sherif

      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
