name: CI

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm ci

      - name: Code Quality
        run: npm run prettier:check

      - name: Tests
        run: npm run test:ci

      - name: build
        run: npm run build

      - name: Deploy to "Surge"
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain ghactions-staging.surge.sh --token ${{ secrets.SURGE_TOKEN }}
