name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - development
  push:
    branches:
      - master
      - development
# For better dependency and readability
# Make multiple jobs with the help of actions/download-artifact
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Code Quality
        run: npm run prettier:check

      - name: Tests
        run: npm run test:ci

      - name: Archive code coverage result
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage

      - name: build
        run: npm run build

      - name: ZIP Assets
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          zip -r build.zip ./build
          zip -r coverage.zip ./coverage

      - name: Create a release
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Staging "Surge"
        if: github.event_name == 'push' && github.ref == 'refs/heads/development'
        run: npx surge --project ./build --domain ghactions-staging.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Deploy to Production "Surge"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx surge --project ./build --domain ghactions.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Upload coverage report "CodeCov"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: jest-react
