name: CI

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Code Quality
        run: npm run prettier:check

      - name: Tests
        run: npm run test:coverage
