name: Matrix

on:
  push:

jobs:
  node-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: Log node version
        run: |
          node -v
          npm -v
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Log node version after node Setup
        run: |
          node -v
          npm -v
