name: Matrix

on:
  # push:
  pull_request:

jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12, 14, 16]
        include:
          - os: windows-latest
            node: 12
            extra-var: nice # add extra keys to specific matrix step ${{ matrix.extra-var }}
        exclude: # Array of exclude matrices
          - os: ubuntu-latest
            node: 12
          - os: macos-latest
            node: 14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: |
          node -v
          npm -v
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Log node version after node Setup
        run: |
          node -v
          npm -v
