name: Matrix

on:
  push:

jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12, 14, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: |
          node -v
          npm -v
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Log node version after node Setup
        run: |
          node -v
          npm -v
